apiVersion: v1
kind: Namespace
metadata:
  name: upstream

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudmeta-config
  namespace: upstream
data:
  sinks: "http://sockeye.default.svc.cluster.local"
  discovery-downstream: "http://cloudmeta.downstream.svc.cluster.local"

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudmeta
  namespace: upstream
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: ko://github.com/n3wscott/cloudevents-discovery/cmd/server
          env:
            - name: SINK
              valueFrom:
                configMapKeyRef:
                  name: cloudmeta-config
                  key: sinks
            - name: DISCOVERY_DOWNSTREAM
              valueFrom:
                configMapKeyRef:
                  name: cloudmeta-config
                  key: discovery-downstream
            - name: DISCOVERY_SERVICES_FILE
              value: /var/run/ko/abc.yaml

